apiVersion: apps/v1
kind: Deployment
metadata:
  name: empleados-k8s-deployment
  labels:
    app: empleados-k8s
spec:
  revisionHistoryLimit: 2
  strategy:
    type: RollingUpdate
  replicas: 2
  selector:
    matchLabels:
      app: empleados-k8s
  template:
    metadata:
      labels:
        app: empleados-k8s
    spec:
      containers:
      - image: hhvelascoa/appempleados:latest
        name: empleados-k8s-pod
        ports:
        - name: http
          containerPort: 8081